### ISSUE TITLE
on close handler prevents process from exiting

### ISSUE THREAD

**Issue by stoically** [kadtools/kad-onion#8]
Hi,

the on close handler here https://github.com/kadtools/kad-onion/blob/master/index.js#L182 prevents my app from being able to exit properly (on Ubuntu 16.04). I'm not sure what's the use-case for this, but maybe it would be possible to disable the behavior via option if its not needed? I could provide a PR.

Best regards

**Comment by bookchin** [comment]
This handler is there in case the for process dies or crashes (or the controller connection closes) while orc is running to start it again and reconnect.  Can you provide anymore information on this behavior? Also can you provide the version of tor you have installed?

**Comment by bookchin** [comment]
Code example I can run and reproduce would be helpful.

**Comment by stoically** [comment]
My tor version is 0.3.1.7. 

A minimum example would be

```javascript
const { app, BrowserWindow } = require('electron');
const level = require('level');
const kad = require('kad');
const kadOnion = require('kad-onion');

app.on('ready', () => {
  win = new BrowserWindow()
  win.loadURL('http://example.com')
  win.webContents.on('did-finish-load', () => {
    const node = kad({
      transport: new kad.HTTPTransport(),
      storage: level('./kad.db'),
      contact: { protocol: 'http:', hostname: '127.0.0.1', port: 48367 }
    });
    node.plugin(kadOnion());
    node.listen(48367, function() {
      console.log('listening');
    });
  });
});

app.on('window-all-closed', () => {
  app.quit();
});
```

and running that with electron.

It doesn't matter how you try to the end the process in the all-closed handler (proccess.exit, tree-kill, kill by pid), it won't end the process since kad-onion is immediately restarting tor.

Another example would be ORC itself. if you close the electron window, the ORC and tor process are still alive.

I understand the need to restart the tor process if it exits unexpectedly, but maybe there's another solution that doesn't keep the process alive if you really want to close it?

**Comment by bookchin** [comment]
I see, I have experienced this too but didn't realize this was the source if the issue. We should be able to listen for process.exit and remove the close listener (unless you suggest a more elegant method).
